-- Generated by `UPDATE_SCHEMA=1 cargo test -p koji-lag store_schema_up_to_date`.
-- The schema koji-lag's SQLite store is migrated to; see src/store.rs MIGRATIONS.

CREATE TABLE builds (
    instance TEXT NOT NULL,
    task_id INTEGER NOT NULL,
    package TEXT,
    nvr TEXT,
    target TEXT,
    owner TEXT,
    scratch INTEGER NOT NULL DEFAULT 0,
    state INTEGER NOT NULL,
    create_ts REAL NOT NULL,
    start_ts REAL,
    completion_ts REAL,
    priority INTEGER,
    host_id INTEGER,
    -- The children generation this build was fetched
    -- under; 0 means its children were never asked for.
    -- Compared against CHILDREN_GEN so a store that
    -- predates a newly collected method knows which
    -- builds are behind, without re-listing anything.
    children_gen INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (instance, task_id)
);

CREATE TABLE channels (
    instance TEXT NOT NULL,
    channel_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    PRIMARY KEY (instance, channel_id)
);

CREATE TABLE host_config (
    instance TEXT NOT NULL,
    host_id INTEGER NOT NULL,
    name TEXT,
    -- Space-separated, as the hub reports it. Kept verbatim rather than
    -- normalised into rows: a handful of revisions carry a Kerberos
    -- principal here instead of architectures, and inventing structure
    -- for that would be inventing meaning.
    arches TEXT,
    enabled INTEGER NOT NULL,
    -- Weight the host accepts at once, which is what Koji schedules
    -- against -- not a task count.
    capacity REAL,
    -- The revision is in force over [create_ts, revoke_ts); a NULL
    -- revoke_ts is the revision still current.
    create_ts REAL NOT NULL,
    revoke_ts REAL,
    PRIMARY KEY (instance, host_id, create_ts)
);

CREATE TABLE hosts (
    instance TEXT NOT NULL,
    host_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    arches TEXT,
    PRIMARY KEY (instance, host_id)
);

CREATE TABLE listed (
    instance TEXT NOT NULL,
    from_ts REAL NOT NULL,
    to_ts REAL NOT NULL,
    -- What the rows in this span were listed with. A
    -- span below LISTING_GEN is treated as a gap, so a
    -- new listing field refreshes itself.
    listing_gen INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE tasks (
    instance TEXT NOT NULL,
    task_id INTEGER NOT NULL,
    parent INTEGER,
    method TEXT NOT NULL,
    arch TEXT NOT NULL,
    package TEXT,
    state INTEGER NOT NULL,
    create_ts REAL NOT NULL,
    start_ts REAL,
    completion_ts REAL,
    host_id INTEGER,
    channel_id INTEGER,
    weight REAL,
    PRIMARY KEY (instance, task_id)
);

CREATE INDEX builds_completion ON builds (instance, completion_ts);

CREATE INDEX builds_unswept ON builds (instance, children_gen, completion_ts);

CREATE INDEX host_config_span ON host_config (instance, create_ts, revoke_ts);

CREATE INDEX listed_span ON listed (instance, from_ts, to_ts);

CREATE INDEX tasks_completion ON tasks (instance, completion_ts);

CREATE INDEX tasks_parent ON tasks (instance, parent);
