// SPDX-License-Identifier: Apache-2.0 OR MIT

use std::io::{IsTerminal, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use clap::Parser;

use fedora_review_digest::checklist::{self, Item, Mark};
use fedora_review_digest::cratesio;
use fedora_review_digest::review::{Generator, Review};

#[derive(Parser)]
#[command(
    version,
    about,
    long_about = None,
    before_help = concat!(env!("CARGO_PKG_NAME"), " ", env!("CARGO_PKG_VERSION"))
)]
struct Cli {
    /// A `fedora-review` result directory, or a review-request bug id
    /// (resolved to `<id>-*` under --reviews-dir).
    #[arg(value_name = "DIR-OR-BUGID")]
    input: String,

    /// Free-form reviewer note placed above the review (e.g. "Looks
    /// good to me!"). Without it, you're prompted (unless --yes).
    #[arg(short, long, value_name = "TEXT")]
    comment: Option<String>,

    /// Accept the inferred checklist marks without prompting.
    #[arg(short = 'y', long)]
    yes: bool,

    /// Base directory to resolve a bug id in (default: current dir).
    #[arg(long, value_name = "DIR", default_value = ".")]
    reviews_dir: PathBuf,

    /// Skip the crates.io latest-version check (offline / faster).
    #[arg(long)]
    no_net: bool,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(&cli) {
        Ok(text) => {
            print!("{text}");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("fedora-review-digest: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: &Cli) -> Result<String, String> {
    let dir = resolve_input(&cli.input, &cli.reviews_dir)?;
    let review = Review::from_dir(&dir)?;
    match review.spec.generator {
        Generator::Rust2Rpm => {}
        Generator::Pyp2Spec => {
            return Err("pyp2spec digests aren't implemented yet (rust2rpm only for now)".into());
        }
        Generator::Unknown => {
            return Err(format!(
                "{} wasn't generated by rust2rpm or pyp2spec — nothing to digest",
                dir.display()
            ));
        }
    }

    // Evidence for the "latest version" item: the latest stable on
    // crates.io. A lookup failure is a warning, not fatal — the item
    // just reports "not checked".
    let crate_latest = if cli.no_net {
        None
    } else {
        match cratesio::fetch_max_stable_version(&review.upstream_name) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("warning: {e}; skipping the latest-version check");
                None
            }
        }
    };

    let mut items = checklist::infer(&review, crate_latest.as_deref());

    // Finalize the marks: interactively by default, or accept the
    // inferred ones with --yes. A non-tty without --yes can't prompt, so
    // fail with a remedy rather than silently rubber-stamping.
    let interactive = !cli.yes && std::io::stdin().is_terminal();
    if !cli.yes {
        if !interactive {
            return Err(
                "not a terminal; pass -y to accept the inferred marks (and --comment for a note)"
                    .into(),
            );
        }
        // Show the inferred findings in full first, then confirm each
        // item — reviewing in context beats deciding line-by-line blind.
        eprintln!(
            "── inferred review for {} {} ──\n",
            review.spec.name, review.spec.version
        );
        eprint!(
            "{}",
            checklist::render_review(review.spec.generator, &items, &review.issues)
        );
        eprintln!("\n── confirm each item ──");
        finalize(&mut items)?;
    }

    let comment = match &cli.comment {
        Some(c) => Some(c.clone()),
        None if interactive => prompt_comment()?,
        None => None,
    };

    let review_block = checklist::render_review(review.spec.generator, &items, &review.issues);
    let post = checklist::render_post_import(review.spec.generator, &review.upstream_name);
    Ok(checklist::assemble(
        comment.as_deref(),
        &review_block,
        &post,
    ))
}

/// Resolve the positional input to a review directory: an existing
/// directory is used as-is; an all-digits argument is treated as a bug
/// id and matched against `<id>-*` under `reviews_dir`.
fn resolve_input(input: &str, reviews_dir: &Path) -> Result<PathBuf, String> {
    let p = Path::new(input);
    if p.is_dir() {
        return Ok(p.to_path_buf());
    }
    if looks_like_bug_id(input) {
        return find_review_dir(reviews_dir, input);
    }
    Err(format!(
        "{input:?} is neither an existing directory nor a bug id"
    ))
}

/// Whether a string is a bare Bugzilla bug id (all digits).
fn looks_like_bug_id(s: &str) -> bool {
    !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit())
}

/// Find the single `<bug_id>-*` directory under `base` (fedora-review's
/// naming). Errors if there are none or more than one.
fn find_review_dir(base: &Path, bug_id: &str) -> Result<PathBuf, String> {
    let prefix = format!("{bug_id}-");
    let mut matches: Vec<PathBuf> = std::fs::read_dir(base)
        .map_err(|e| format!("reading {}: {e}", base.display()))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.is_dir()
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.starts_with(&prefix))
        })
        .collect();
    match matches.len() {
        0 => Err(format!(
            "no review dir for bug {bug_id} under {} (looked for {prefix}*)",
            base.display()
        )),
        1 => Ok(matches.pop().unwrap()),
        _ => Err(format!(
            "multiple {prefix}* dirs under {}; pass the path directly",
            base.display()
        )),
    }
}

/// Walk the checklist, prompting +1 / 0 / -1 per item (Enter accepts the
/// inferred default); for a caveat/fail, also prompt for the note.
fn finalize(items: &mut [Item]) -> Result<(), String> {
    eprintln!("+1 pass / 0 caveat / -1 fail — Enter accepts the inferred mark\n");
    let n = items.len();
    for (i, it) in items.iter_mut().enumerate() {
        let inferred = it.mark;
        let vote = prompt_vote(i + 1, n, it)?;
        it.mark = Mark::from_vote(vote).expect("vote validated");
        match it.mark {
            // Keep an evidence note on an unchanged pass; drop a
            // now-stale caveat/fail note if the reviewer upgraded to pass.
            Mark::Pass => {
                if inferred != Mark::Pass {
                    it.note = None;
                }
            }
            // A caveat/fail needs a justification — prompt for it (Enter
            // keeps the inferred placeholder).
            Mark::Caveat | Mark::Fail => it.note = prompt_note(it)?,
        }
    }
    eprintln!();
    Ok(())
}

/// Prompt for one item's vote, defaulting to its inferred mark.
fn prompt_vote(idx: usize, total: usize, it: &Item) -> Result<i32, String> {
    let default = it.mark.vote();
    // Show the evidence/justification inline so the call is made *with*
    // the finding in view, not after committing to a vote.
    let note = it
        .note
        .as_deref()
        .map(|n| format!(" ({n})"))
        .unwrap_or_default();
    loop {
        eprint!(
            "[{idx}/{total}] {} {}{note} [{:+}]: ",
            it.mark.emoji(),
            it.label,
            default
        );
        let _ = std::io::stderr().flush();
        let line = read_line()?;
        let s = line.trim();
        if s.is_empty() {
            return Ok(default);
        }
        match s {
            "+1" | "1" => return Ok(1),
            "0" => return Ok(0),
            "-1" => return Ok(-1),
            _ => eprintln!("  enter +1, 0, or -1"),
        }
    }
}

/// Prompt for a caveat/fail justification, defaulting to the inferred
/// note (Enter keeps it).
fn prompt_note(it: &Item) -> Result<Option<String>, String> {
    let default = it.note.clone().unwrap_or_default();
    eprint!("    note [{default}]: ");
    let _ = std::io::stderr().flush();
    let line = read_line()?;
    let s = line.trim();
    Ok(if s.is_empty() {
        it.note.clone()
    } else {
        Some(s.to_string())
    })
}

/// Prompt for the free-form top comment: read lines until a blank line
/// or EOF. `None` if nothing was entered.
fn prompt_comment() -> Result<Option<String>, String> {
    eprintln!("Top comment (optional) — end with an empty line:");
    let mut lines: Vec<String> = Vec::new();
    loop {
        let line = read_line()?;
        if line.is_empty() {
            break; // EOF
        }
        let trimmed = line.trim_end_matches('\n');
        if trimmed.is_empty() {
            break; // blank line ends input
        }
        lines.push(trimmed.to_string());
    }
    Ok(if lines.is_empty() {
        None
    } else {
        Some(lines.join("\n"))
    })
}

/// Read a line from stdin; empty string signals EOF.
fn read_line() -> Result<String, String> {
    let mut line = String::new();
    std::io::stdin()
        .read_line(&mut line)
        .map_err(|e| format!("reading input: {e}"))?;
    Ok(line)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bug_id_detection() {
        assert!(looks_like_bug_id("2489102"));
        assert!(!looks_like_bug_id("2489102-rust-foo"));
        assert!(!looks_like_bug_id("rust-foo"));
        assert!(!looks_like_bug_id(""));
    }
}
