// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Parse a `fedora-review -b <bug>` result directory into the facts the
//! digest needs: which generator produced the spec, the package
//! identity, and the signals that inform each checklist mark. The
//! file-reading entry point is [`Review::from_dir`]; the parsing itself
//! is split into pure functions so it can be unit-tested against
//! recorded fixtures without a real review tree.

use std::path::{Path, PathBuf};

/// The tool a spec was generated by — selects the checklist and the
/// post-import boilerplate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Generator {
    /// `rust2rpm` — a `rust-<crate>` package.
    Rust2Rpm,
    /// `pyp2spec` — a `python-<project>` package (support is stubbed).
    Pyp2Spec,
    /// Neither marker found — not an auto-generated spec we digest.
    Unknown,
}

/// A fedora-review MUST failure (from review.json `issues`) — something
/// the reviewer should address before approving.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Issue {
    /// The check name, e.g. `CheckFileDuplicates`.
    pub name: String,
    /// The check's description (phrased as the passing criterion).
    pub text: String,
    /// The actual finding, when fedora-review attached one (e.g.
    /// `warning: File listed twice: …`) — the actionable detail.
    pub note: Option<String>,
}

/// Fields read from the spec file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpecInfo {
    pub generator: Generator,
    /// `Name:` — e.g. `rust-trustfall_core`.
    pub name: String,
    /// `Version:`.
    pub version: String,
    /// `License:`.
    pub license: String,
    /// Whether the test suite is built/run (rust2rpm's `%bcond check 1`,
    /// or a `%check` block when no bcond gates it).
    pub tests_enabled: bool,
    /// Whether the `%check` section skips tests (`%cargo_test` with
    /// `--skip`), i.e. tests run but not all of them.
    pub tests_skipped: bool,
    /// Whether a `%license` entry ships a license file.
    pub has_license_file: bool,
    /// Whether the license file is included *manually* — added as a
    /// `Source` (because upstream's crate doesn't ship it) rather than
    /// coming from the crate itself.
    pub license_manual: bool,
    /// Whether a pull-request comment precedes that manual license
    /// `Source` (an upstream fix is in flight).
    pub license_fix_submitted: bool,
    /// Whether the package installs a binary in `%{_bindir}` — for a
    /// Rust binary, its statically linked deps' licenses must be folded
    /// into `License:`, so the digest adds a check for that.
    pub ships_binary: bool,
}

/// The facts extracted from a review directory.
#[derive(Debug, Clone)]
pub struct Review {
    pub spec: SpecInfo,
    /// Upstream name with the `rust-`/`python-` prefix stripped — the
    /// `$crate` in the rust-sig post-import boilerplate.
    pub upstream_name: String,
    /// The `license =` value from the packaged crate's `Cargo.toml`
    /// (read from the unpacked devel RPM), for the license evidence;
    /// `None` if not found.
    pub cargo_license: Option<String>,
    /// A binary RPM was produced (the build succeeded).
    pub build_ok: bool,
    /// rpmlint reported no errors and no warnings.
    pub rpmlint_clean: bool,
    /// fedora-review MUST failures.
    pub issues: Vec<Issue>,
    /// For a binary crate, the statically-linked dependency license
    /// evidence (build-log summary vs the spec's folded `License:`);
    /// `None` for a library crate or when the section can't be found.
    pub static_deps: Option<StaticDeps>,
}

/// Statically-linked dependency license evidence for a binary crate: the
/// license summary rust2rpm wrote to the build log, and the matching
/// `# <expr>` block above the binary subpackage's folded `License:` line
/// in the spec.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StaticDeps {
    /// License expressions from the build log's `LICENSE SUMMARY` block
    /// (empty if the build log wasn't found).
    pub summary: Vec<String>,
    /// License expressions listed as `# <expr>` comments above the
    /// binary subpackage's `License:` line in the spec.
    pub spec_listed: Vec<String>,
    /// The raw spec section (the `# <expr>` block plus the `License:`
    /// line, and a trailing `LICENSE.dependencies` note if any), for the
    /// reviewer to inspect.
    pub spec_section: String,
}

impl StaticDeps {
    /// Build-log summary licenses not found in the spec's `# <expr>`
    /// listing — i.e. licenses that should be folded into `License:` but
    /// aren't. Empty when the build log wasn't read (nothing to compare).
    pub fn missing(&self) -> Vec<&str> {
        self.summary
            .iter()
            .filter(|s| !self.spec_listed.iter().any(|l| l == *s))
            .map(String::as_str)
            .collect()
    }
}

impl Review {
    /// Read and parse a `fedora-review` result directory.
    pub fn from_dir(dir: &Path) -> Result<Review, String> {
        let spec_path = find_spec(dir).ok_or_else(|| {
            format!(
                "no .spec found under {} (looked in srpm-unpacked/, srpm/)",
                dir.display()
            )
        })?;
        let spec_text = std::fs::read_to_string(&spec_path)
            .map_err(|e| format!("reading {}: {e}", spec_path.display()))?;
        let spec = parse_spec(&spec_text);
        let upstream_name = strip_prefix(&spec.name);

        let cargo_license = find_cargo_toml(dir)
            .and_then(|p| std::fs::read_to_string(p).ok())
            .as_deref()
            .and_then(parse_cargo_license);
        let build_ok = built_binary_rpm(dir);
        let rpmlint_clean = std::fs::read_to_string(dir.join("rpmlint.txt"))
            .ok()
            .as_deref()
            .map(rpmlint_clean)
            .unwrap_or(false);
        let mut issues = std::fs::read_to_string(dir.join("review.json"))
            .ok()
            .as_deref()
            .map(parse_issues)
            .unwrap_or_default();
        // A file listed twice because it lives in the crate instdir *and*
        // is labeled %doc/%license (LICENSE, README, …) is standard for
        // rust2rpm packages, not a real problem — drop it.
        if spec.generator == Generator::Rust2Rpm {
            issues.retain(|i| !is_benign_instdir_dup(i));
        }

        // For a binary crate, gather the static-dep license evidence: the
        // spec's folded-License section, checked against the build log's
        // LICENSE SUMMARY.
        let static_deps = if spec.ships_binary {
            parse_spec_license_section(&spec_text).map(|(spec_listed, spec_section)| {
                let summary = std::fs::read_to_string(dir.join("results/build.log"))
                    .ok()
                    .as_deref()
                    .map(parse_license_summary)
                    .unwrap_or_default();
                StaticDeps {
                    summary,
                    spec_listed,
                    spec_section,
                }
            })
        } else {
            None
        };

        Ok(Review {
            spec,
            upstream_name,
            cargo_license,
            build_ok,
            rpmlint_clean,
            issues,
            static_deps,
        })
    }
}

/// Locate the spec file in a review dir. Prefer `srpm/*.spec` — the
/// proper submitted spec — over `srpm-unpacked/*.spec`, which is the
/// copy unpacked from the built SRPM and has its rpmautospec macros
/// (`%autorelease`/`%autochangelog`) expanded into a preamble.
pub fn find_spec(dir: &Path) -> Option<PathBuf> {
    for sub in ["srpm", "srpm-unpacked"] {
        if let Ok(entries) = std::fs::read_dir(dir.join(sub)) {
            for e in entries.flatten() {
                let p = e.path();
                if p.extension().is_some_and(|x| x == "spec") {
                    return Some(p);
                }
            }
        }
    }
    None
}

/// Detect the generator from the spec's `# Generated by …` marker.
/// It's usually line 1, but nothing guarantees it stays there — lines
/// could be prepended above it — so scan the whole spec rather than just
/// the head.
pub fn detect_generator(spec: &str) -> Generator {
    for line in spec.lines() {
        let l = line.to_ascii_lowercase();
        if l.contains("generated by rust2rpm") {
            return Generator::Rust2Rpm;
        }
        if l.contains("generated by pyp2spec") {
            return Generator::Pyp2Spec;
        }
    }
    Generator::Unknown
}

/// Parse the spec fields the checklist needs.
pub fn parse_spec(spec: &str) -> SpecInfo {
    let field = |key: &str| -> String {
        spec.lines()
            .find_map(|l| {
                let l = l.trim();
                l.strip_prefix(key)
                    .filter(|_| l.starts_with(key))
                    .map(|v| v.trim().to_string())
            })
            .unwrap_or_default()
    };
    let (license_manual, license_fix) = detect_manual_license(spec);
    SpecInfo {
        generator: detect_generator(spec),
        name: field("Name:"),
        version: field("Version:"),
        license: field("License:"),
        tests_enabled: tests_enabled(spec),
        tests_skipped: check_section_skips(spec),
        has_license_file: spec
            .lines()
            .any(|l| l.trim_start().starts_with("%license ")),
        license_manual,
        license_fix_submitted: license_fix,
        ships_binary: spec
            .lines()
            .any(|l| l.trim_start().starts_with("%{_bindir}")),
    }
}

/// Whether the `%check` section runs `%cargo_test` with `--skip`, i.e.
/// some tests are excluded (not all run).
fn check_section_skips(spec: &str) -> bool {
    let mut in_check = false;
    for l in spec.lines() {
        let t = l.trim();
        if t == "%check" {
            in_check = true;
            continue;
        }
        if in_check {
            if is_section_start(t) {
                break;
            }
            if t.contains("--skip") {
                return true;
            }
        }
    }
    false
}

/// Whether a trimmed line opens a new spec section (ends the previous).
fn is_section_start(t: &str) -> bool {
    const SECTIONS: &[&str] = &[
        "%prep",
        "%build",
        "%install",
        "%check",
        "%files",
        "%changelog",
        "%package",
        "%description",
        "%pre",
        "%post",
        "%preun",
        "%postun",
    ];
    SECTIONS
        .iter()
        .any(|s| t == *s || t.starts_with(&format!("{s} ")))
}

/// Detect a manually-added license file: a `Source` whose filename is a
/// license file (upstream's crate didn't ship one, so the packager adds
/// it). Returns `(manual, fix_submitted)`, where `fix_submitted` is true
/// when a pull-request comment precedes that `Source` line.
fn detect_manual_license(spec: &str) -> (bool, bool) {
    let lines: Vec<&str> = spec.lines().collect();
    for (i, l) in lines.iter().enumerate() {
        if let Some(val) = source_value(l.trim())
            && is_license_filename(val)
        {
            return (true, preceding_comments_have_pr(&lines, i));
        }
    }
    (false, false)
}

/// The value of a `Source:` / `Source<N>:` directive, else `None`.
fn source_value(line: &str) -> Option<&str> {
    let rest = line.strip_prefix("Source")?;
    let (num, after) = rest.split_once(':')?;
    num.chars()
        .all(|c| c.is_ascii_digit())
        .then(|| after.trim())
}

/// Whether a path/URL's last segment names a license file.
fn is_license_filename(val: &str) -> bool {
    let base = val.rsplit('/').next().unwrap_or(val).to_uppercase();
    base.contains("LICENSE") || base.contains("LICENCE") || base.contains("COPYING")
}

/// Whether the comment lines immediately above `idx` mention a pull
/// request (an upstream fix in flight).
fn preceding_comments_have_pr(lines: &[&str], idx: usize) -> bool {
    for l in lines[..idx].iter().rev() {
        let t = l.trim();
        if t.is_empty() {
            continue;
        }
        if let Some(comment) = t.strip_prefix('#') {
            let c = comment.to_lowercase();
            if c.contains("/pull/") || c.contains("pull request") {
                return true;
            }
        } else {
            break; // a non-comment line ends the comment block
        }
    }
    false
}

/// Locate the packaged crate's `Cargo.toml` — the devel RPM installs the
/// crate sources under `…/usr/share/cargo/registry/<crate>/`, which
/// fedora-review unpacks into `rpms-unpacked/`.
fn find_cargo_toml(dir: &Path) -> Option<PathBuf> {
    find_named(&dir.join("rpms-unpacked"), "Cargo.toml", 8)
}

/// First file named `name` under `dir`, searched depth-first up to
/// `depth` levels (avoids pulling in a directory-walk dependency).
fn find_named(dir: &Path, name: &str, depth: usize) -> Option<PathBuf> {
    if depth == 0 {
        return None;
    }
    let mut subdirs = Vec::new();
    for e in std::fs::read_dir(dir).ok()?.flatten() {
        let p = e.path();
        if p.is_dir() {
            subdirs.push(p);
        } else if p.file_name().and_then(|n| n.to_str()) == Some(name) {
            return Some(p);
        }
    }
    subdirs.iter().find_map(|s| find_named(s, name, depth - 1))
}

/// The `license = "…"` value from a `Cargo.toml`'s `[package]` table.
/// `None` if absent or expressed only via `license-file`.
pub fn parse_cargo_license(cargo_toml: &str) -> Option<String> {
    cargo_toml.lines().find_map(|l| {
        let rest = l.trim().strip_prefix("license")?.trim_start();
        let val = rest.strip_prefix('=')?.trim().trim_matches('"');
        (!val.is_empty()).then(|| val.to_string())
    })
}

/// License expressions from a build log's `### BEGIN LICENSE SUMMARY ###`
/// … `###  END LICENSE SUMMARY  ###` block — each a `# <expr>` line that
/// rust2rpm emits listing the bundled dependencies' licenses. Empty if
/// the block isn't present.
pub fn parse_license_summary(build_log: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_summary = false;
    for line in build_log.lines() {
        let t = line.trim();
        if t.contains("BEGIN LICENSE SUMMARY") {
            in_summary = true;
            continue;
        }
        if t.contains("END LICENSE SUMMARY") {
            break;
        }
        if in_summary && let Some(expr) = t.strip_prefix('#') {
            let expr = expr.trim();
            if !expr.is_empty() {
                out.push(expr.to_string());
            }
        }
    }
    out
}

/// The binary subpackage's static-dep license section in a spec: the
/// contiguous `# <expr>` comment block immediately above a `License:`
/// line (the folded license for a bundled binary). Returns the listed
/// license expressions (a `LICENSE.dependencies` note is excluded from
/// the list but kept in the raw text) and the raw section — the comment
/// block, the `License:` line, and a trailing `LICENSE.dependencies` note
/// if present — for the reviewer to inspect. `None` when no `License:`
/// line has such a comment block above it (e.g. a library crate).
pub fn parse_spec_license_section(spec: &str) -> Option<(Vec<String>, String)> {
    let lines: Vec<&str> = spec.lines().collect();
    for (i, line) in lines.iter().enumerate() {
        if !line.trim_start().starts_with("License:") {
            continue;
        }
        // Walk upward over the contiguous comment block above it.
        let mut start = i;
        while start > 0 && lines[start - 1].trim_start().starts_with('#') {
            start -= 1;
        }
        if start == i {
            continue; // no comment block — not the folded-license section
        }
        let listed: Vec<String> = lines[start..i]
            .iter()
            .map(|l| l.trim_start().trim_start_matches('#').trim())
            .filter(|c| !c.is_empty() && !c.contains("LICENSE.dependencies"))
            .map(str::to_string)
            .collect();
        if listed.is_empty() {
            continue; // comments weren't license expressions
        }
        // Extend the section past the License: line to a trailing
        // `LICENSE.dependencies` note, if one follows.
        let mut end = i;
        if let Some(next) = lines.get(i + 1)
            && next.trim_start().starts_with('#')
            && next.contains("LICENSE.dependencies")
        {
            end = i + 1;
        }
        return Some((listed, lines[start..=end].join("\n")));
    }
    None
}

/// Whether the spec builds/runs its test suite. rust2rpm gates it with
/// `%bcond check <0|1>`; otherwise infer from a `%check` section.
pub fn tests_enabled(spec: &str) -> bool {
    for l in spec.lines() {
        let l = l.trim();
        // `%bcond check 1` (enabled) / `%bcond check 0` (disabled).
        if let Some(rest) = l.strip_prefix("%bcond check ") {
            return rest.trim() == "1";
        }
        // Legacy spelling.
        if l == "%bcond_with check" {
            return false;
        }
        if l == "%bcond_without check" {
            return true;
        }
    }
    // No bcond — enabled iff there's a %check section.
    spec.lines().any(|l| l.trim_start() == "%check")
}

/// Whether rpmlint reported a clean run (`0 errors, … 0 warnings`).
pub fn rpmlint_clean(rpmlint: &str) -> bool {
    rpmlint.lines().any(|l| {
        let l = l.trim();
        l.contains("0 errors") && l.contains("0 warnings")
    })
}

/// The fedora-review MUST failures from a review.json body.
pub fn parse_issues(json: &str) -> Vec<Issue> {
    let Ok(v) = serde_json::from_str::<serde_json::Value>(json) else {
        return Vec::new();
    };
    v.get("issues")
        .and_then(|i| i.as_array())
        .map(|arr| {
            arr.iter()
                .filter(|it| it.get("result").and_then(|r| r.as_str()) == Some("fail"))
                .map(|it| Issue {
                    name: it
                        .get("name")
                        .and_then(|n| n.as_str())
                        .unwrap_or("")
                        .to_string(),
                    text: it
                        .get("text")
                        .and_then(|t| t.as_str())
                        .unwrap_or("")
                        .to_string(),
                    note: it
                        .get("note")
                        .and_then(|n| n.as_str())
                        .filter(|s| !s.trim().is_empty())
                        .map(str::to_string),
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Whether an issue is a benign "File listed twice" that rust2rpm
/// packages always trip — not a real defect. The crate sources are
/// installed verbatim under the crate instdir
/// (`…/usr/share/cargo/registry/<crate>/`), and any file there that's
/// *also* labeled `%doc` or `%license` (LICENSE, README, …) gets listed
/// twice. A duplicate whose path is under that instdir is therefore
/// expected; one elsewhere is a genuine packaging mistake.
pub fn is_benign_instdir_dup(issue: &Issue) -> bool {
    if issue.name != "CheckFileDuplicates" {
        return false;
    }
    let note = issue.note.as_deref().unwrap_or("");
    note.contains("/usr/share/cargo/registry/")
}

/// Strip the `rust-`/`python-` package prefix to get the upstream name.
fn strip_prefix(name: &str) -> String {
    name.strip_prefix("rust-")
        .or_else(|| name.strip_prefix("python-"))
        .unwrap_or(name)
        .to_string()
}

/// Whether the build produced a binary (non-`.src`) RPM in `results/`.
fn built_binary_rpm(dir: &Path) -> bool {
    let Ok(entries) = std::fs::read_dir(dir.join("results")) else {
        return false;
    };
    entries.flatten().any(|e| {
        let n = e.file_name();
        let n = n.to_string_lossy();
        n.ends_with(".rpm") && !n.ends_with(".src.rpm")
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const RUST_SPEC: &str = "\
# Generated by rust2rpm 28
%bcond check 1

Name:           rust-trustfall_core
Version:        0.8.1
Summary:        Trustfall query engine
License:        Apache-2.0

%files devel
%license %{crate_instdir}/LICENSE.txt

%check
%cargo_test
";

    #[test]
    fn detect_generator_reads_the_marker() {
        assert_eq!(detect_generator(RUST_SPEC), Generator::Rust2Rpm);
        assert_eq!(
            detect_generator("# Generated by pyp2spec 1.2\nName: python-foo\n"),
            Generator::Pyp2Spec
        );
        assert_eq!(detect_generator("Name: hand-written\n"), Generator::Unknown);
        // The marker need not be line 1 — lines may be prepended above it.
        let with_header = "\
# vim: set ft=spec:
%global some_local_macro 1

# Generated by rust2rpm 28
Name: rust-foo
";
        assert_eq!(detect_generator(with_header), Generator::Rust2Rpm);
    }

    #[test]
    fn parse_spec_extracts_fields() {
        let s = parse_spec(RUST_SPEC);
        assert_eq!(s.generator, Generator::Rust2Rpm);
        assert_eq!(s.name, "rust-trustfall_core");
        assert_eq!(s.version, "0.8.1");
        assert_eq!(s.license, "Apache-2.0");
        assert!(s.tests_enabled);
        assert!(!s.tests_skipped); // plain %cargo_test, no --skip
        assert!(s.has_license_file);
        assert!(!s.license_manual); // ships its own license
        // A library crate ships no binary.
        assert!(!s.ships_binary);
    }

    #[test]
    fn license_summary_parsed_from_build_log() {
        let log = "\
some build output
### BEGIN LICENSE SUMMARY ###
# Apache-2.0 OR MIT
# BSD-3-Clause
# MIT
###  END LICENSE SUMMARY  ###
more output
";
        assert_eq!(
            parse_license_summary(log),
            vec!["Apache-2.0 OR MIT", "BSD-3-Clause", "MIT"]
        );
        assert!(parse_license_summary("no summary here").is_empty());
    }

    #[test]
    fn spec_license_section_found_above_folded_license() {
        let spec = "\
License:        BSD-3-Clause
URL:            https://example.com

%package     -n %{crate}
Summary:        %{summary}

# Apache-2.0 OR MIT
# BSD-3-Clause
# MIT
License: (Apache-2.0 OR MIT) AND BSD-3-Clause AND MIT
";
        let (listed, section) = parse_spec_license_section(spec).unwrap();
        // The first License: (no comment block above it) is skipped; the
        // folded subpackage License: with its # block is the match.
        assert_eq!(listed, vec!["Apache-2.0 OR MIT", "BSD-3-Clause", "MIT"]);
        assert!(section.starts_with("# Apache-2.0 OR MIT"));
        assert!(section.trim_end().ends_with("AND MIT"));
        // A library spec (no # block above License:) yields nothing.
        assert!(parse_spec_license_section("License: MIT\n").is_none());
    }

    #[test]
    fn static_deps_missing_reports_the_gap() {
        let sd = StaticDeps {
            summary: vec!["MIT".into(), "MPL-2.0".into(), "BSD-3-Clause".into()],
            spec_listed: vec!["MIT".into(), "BSD-3-Clause".into()],
            spec_section: String::new(),
        };
        assert_eq!(sd.missing(), vec!["MPL-2.0"]);
    }

    #[test]
    fn check_section_skips_detected() {
        let with_skip = "%check\n%cargo_test -- --skip foo --skip bar\n%changelog\n";
        assert!(check_section_skips(with_skip));
        let plain = "%check\n%cargo_test\n%changelog\n";
        assert!(!check_section_skips(plain));
        // A --skip outside %check doesn't count.
        let elsewhere = "%build\n# --skip noted\n%check\n%cargo_test\n";
        assert!(!check_section_skips(elsewhere));
    }

    #[test]
    fn manual_license_with_pr_comment_is_detected() {
        // mdbook-summary shape: a PR comment, then a LICENSE Source.
        let spec = "\
Source:         %{crates_source}
# * https://github.com/rust-lang/mdBook/pull/3135
Source2:        https://github.com/rust-lang/mdBook/raw/refs/tags/v0.5.3/LICENSE
";
        let (manual, fix) = detect_manual_license(spec);
        assert!(manual);
        assert!(fix);
    }

    #[test]
    fn manual_license_without_pr_comment_has_no_fix() {
        let spec = "Source: %{crates_source}\nSource2: https://example/COPYING\n";
        let (manual, fix) = detect_manual_license(spec);
        assert!(manual);
        assert!(!fix);
    }

    #[test]
    fn no_manual_license_when_only_the_crate_source() {
        let spec = "Source: %{crates_source}\n";
        assert_eq!(detect_manual_license(spec), (false, false));
    }

    #[test]
    fn ships_binary_detects_bindir_in_files() {
        let spec = "Name: rust-foo\n%files\n%{_bindir}/foo\n";
        assert!(parse_spec(spec).ships_binary);
    }

    #[test]
    fn parse_cargo_license_reads_the_field() {
        assert_eq!(
            parse_cargo_license("[package]\nname = \"x\"\nlicense = \"Apache-2.0\"\n").as_deref(),
            Some("Apache-2.0")
        );
        // `license-file` (no SPDX expression) → None.
        assert_eq!(
            parse_cargo_license("[package]\nlicense-file = \"LICENSE\"\n"),
            None
        );
        assert_eq!(parse_cargo_license("name = \"x\"\n"), None);
    }

    #[test]
    fn tests_enabled_respects_the_bcond() {
        assert!(tests_enabled("%bcond check 1\n%check\n"));
        assert!(!tests_enabled("%bcond check 0\n%check\n"));
        assert!(!tests_enabled("%bcond_with check\n"));
        assert!(tests_enabled("%bcond_without check\n"));
        // No bcond: enabled iff a %check section exists.
        assert!(tests_enabled("Name: x\n%check\n%cargo_test\n"));
        assert!(!tests_enabled("Name: x\n%install\n"));
    }

    #[test]
    fn rpmlint_clean_reads_the_summary() {
        assert!(rpmlint_clean(
            " 3 packages and 0 specfiles checked; 0 errors, 0 warnings, 13 filtered, 0 badness"
        ));
        assert!(!rpmlint_clean("1 packages checked; 2 errors, 0 warnings"));
        assert!(!rpmlint_clean(""));
    }

    #[test]
    fn parse_issues_keeps_only_fails() {
        let json = r#"{"issues": [
            {"name": "CheckFileDuplicates", "text": "no duplicates in %files.", "result": "fail"},
            {"name": "CheckSomethingPassing", "text": "ok", "result": "pass"}
        ], "results": {}}"#;
        let issues = parse_issues(json);
        assert_eq!(issues.len(), 1);
        assert_eq!(issues[0].name, "CheckFileDuplicates");
        assert_eq!(parse_issues("not json"), vec![]);
        assert_eq!(parse_issues(r#"{"results": {}}"#), vec![]);
    }

    #[test]
    fn benign_instdir_dup_is_recognized() {
        // A license file in the crate instdir, also %license'd.
        let lic = Issue {
            name: "CheckFileDuplicates".to_string(),
            text: "no dupes".to_string(),
            note: Some(
                "warning: File listed twice: \
                 /usr/share/cargo/registry/foo-1.0/LICENSE.txt"
                    .to_string(),
            ),
        };
        assert!(is_benign_instdir_dup(&lic));
        // Any other instdir file (README, …) %doc'd is equally benign.
        let readme = Issue {
            name: "CheckFileDuplicates".to_string(),
            text: "no dupes".to_string(),
            note: Some(
                "warning: File listed twice: \
                 /usr/share/cargo/registry/oncemutex-0.1.1/README.md"
                    .to_string(),
            ),
        };
        assert!(is_benign_instdir_dup(&readme));
        // A duplicate outside the crate instdir is a real issue.
        let other = Issue {
            name: "CheckFileDuplicates".to_string(),
            text: "no dupes".to_string(),
            note: Some("warning: File listed twice: /usr/bin/foo".to_string()),
        };
        assert!(!is_benign_instdir_dup(&other));
        // A different check is never suppressed.
        let unrelated = Issue {
            name: "CheckSomethingElse".to_string(),
            text: "x".to_string(),
            note: Some("/usr/share/cargo/registry/foo-1.0/LICENSE.txt".to_string()),
        };
        assert!(!is_benign_instdir_dup(&unrelated));
    }
}
