[package]
name = "sandogasa-meetbot"
description = "HTTP client for meetbot.fedoraproject.org's meeting search endpoint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sandogasa-cli = { workspace = true, features = ["http"] }
chrono = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
wiremock = { workspace = true }
