.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sandogasa-pkg-acl 1  sandogasa "Sandogasa Manual"
.SH NAME
sandogasa\-pkg\-acl \- View and manage Fedora package ACLs via the Pagure dist\-git API
.SH SYNOPSIS
\fBsandogasa\-pkg\-acl\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
View and manage Fedora package ACLs via the Pagure dist\-git API
.SH OPTIONS
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH COMMANDS
.SS sandogasa-pkg-acl apply
\fBsandogasa\-pkg\-acl apply\fR [\fB\-\-json\fR] [\fB\-\-strict\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICONFIG\fR> <\fIPACKAGES\fR> 
.PP
Apply ACLs from a TOML config file
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-\-strict\fR
Downgrade access if already higher than requested
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICONFIG\fR>
Path to TOML config file
.TP
<\fIPACKAGES\fR>
Package name(s)
.SS sandogasa-pkg-acl config
\fBsandogasa\-pkg\-acl config\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.PP
Set up or verify stored API token
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SS sandogasa-pkg-acl give
\fBsandogasa\-pkg\-acl give\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIUSER\fR> <\fIPACKAGES\fR> 
.PP
Give package ownership to another user
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIUSER\fR>
Username of new owner
.TP
<\fIPACKAGES\fR>
Package name(s)
.SS sandogasa-pkg-acl remove
\fBsandogasa\-pkg\-acl remove\fR [\fB\-\-json\fR] [\fB\-\-user\fR] [\fB\-\-group\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.PP
Remove all ACLs for a user or group
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-\-user\fR \fI<USER>\fR
User to remove ACLs for
.TP
\fB\-\-group\fR \fI<GROUP>\fR
Group to remove ACLs for
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name
.SS sandogasa-pkg-acl set
\fBsandogasa\-pkg\-acl set\fR [\fB\-\-json\fR] [\fB\-\-user\fR] [\fB\-\-group\fR] <\fB\-\-level\fR> [\fB\-\-strict\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.PP
Set an ACL level for a user or group
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-\-user\fR \fI<USER>\fR
User to set ACL for
.TP
\fB\-\-group\fR \fI<GROUP>\fR
Group to set ACL for
.TP
\fB\-\-level\fR \fI<LEVEL>\fR
ACL level (ticket, collaborator, commit, admin)
.TP
\fB\-\-strict\fR
Downgrade access if already higher than requested
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name
.SS sandogasa-pkg-acl show
\fBsandogasa\-pkg\-acl show\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.PP
Show current ACLs for a package
.TP
\fB\-\-json\fR
Output machine\-readable JSON
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name
